//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanGiay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoesShopEntities : DbContext
    {
        public ShoesShopEntities()
            : base("name=ShoesShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Admin> tb_Admin { get; set; }
        public virtual DbSet<tb_AnhMatHang> tb_AnhMatHang { get; set; }
        public virtual DbSet<tb_BangGiaShip> tb_BangGiaShip { get; set; }
        public virtual DbSet<tb_BangGiaSP> tb_BangGiaSP { get; set; }
        public virtual DbSet<tb_BangGioiTinh> tb_BangGioiTinh { get; set; }
        public virtual DbSet<tb_BangKichThuoc> tb_BangKichThuoc { get; set; }
        public virtual DbSet<tb_BangMauSP> tb_BangMauSP { get; set; }
        public virtual DbSet<tb_Banner> tb_Banner { get; set; }
        public virtual DbSet<tb_ChiTietDonMuaHang> tb_ChiTietDonMuaHang { get; set; }
        public virtual DbSet<tb_DanhGiaTraiNghiem> tb_DanhGiaTraiNghiem { get; set; }
        public virtual DbSet<tb_DanhMuc> tb_DanhMuc { get; set; }
        public virtual DbSet<tb_DonMuaHang> tb_DonMuaHang { get; set; }
        public virtual DbSet<tb_GioiTinhMatHang> tb_GioiTinhMatHang { get; set; }
        public virtual DbSet<tb_MatHang> tb_MatHang { get; set; }
        public virtual DbSet<tb_MauMatHang> tb_MauMatHang { get; set; }
        public virtual DbSet<tb_MoTaDonHang> tb_MoTaDonHang { get; set; }
        public virtual DbSet<tb_NguoiDung> tb_NguoiDung { get; set; }
        public virtual DbSet<tb_SanPham> tb_SanPham { get; set; }
        public virtual DbSet<tb_SizeMatHang> tb_SizeMatHang { get; set; }
    }
}
