//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BangGioiTinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_BangGioiTinh()
        {
            this.tb_GioiTinhMatHang = new HashSet<tb_GioiTinhMatHang>();
            this.tb_MoTaDonHang = new HashSet<tb_MoTaDonHang>();
        }
    
        public int ID { get; set; }
        public string GioiTinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_GioiTinhMatHang> tb_GioiTinhMatHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MoTaDonHang> tb_MoTaDonHang { get; set; }
    }
}
