//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChiTietDonMuaHang
    {
        public int ID { get; set; }
        public Nullable<int> ID_MoTaDonHang { get; set; }
        public Nullable<int> ID_SanPham { get; set; }
    
        public virtual tb_MoTaDonHang tb_MoTaDonHang { get; set; }
        public virtual tb_SanPham tb_SanPham { get; set; }
    }
}
