//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_DonMuaHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_DonMuaHang()
        {
            this.tb_MoTaDonHang = new HashSet<tb_MoTaDonHang>();
        }
    
        public int ID { get; set; }
        [DisplayName("ID người dùng")]
        public Nullable<int> ID_NguoiDung { get; set; }

        [DisplayName("Trạng thái")]
        public Nullable<int> TrangThai { get; set; }

        [DisplayName("Họ tên")]
        public string HoTen { get; set; }

        [DisplayName("Số điện thoại")]
        public string SDT { get; set; }

        [DisplayName("Địa chỉ giao hàng")]
        public string DiaChiGiaoHang { get; set; }

        [DisplayName("Nhà riêng")]
        public Nullable<bool> NhaRieng { get; set; }

        [DisplayName("Ngày đặt")]
        public Nullable<System.DateTime> NgayDat { get; set; }

        [DisplayName("Ngày duyệt")]
        public Nullable<System.DateTime> NgayDuyet { get; set; }

        [DisplayName("Ngày dự kiến")]
        public Nullable<System.DateTime> NgayDuKien { get; set; }

        [DisplayName("Tổng tiền")]
        public Nullable<decimal> TongTien { get; set; }

        [DisplayName("Tiền ship")]
        public Nullable<decimal> TienShip { get; set; }

        [DisplayName("Tổng cộng")]
        public Nullable<decimal> TongCong { get; set; }

        [DisplayName("Hình thức thanh toán")]
        public string HinhThucTT { get; set; }

        public virtual tb_NguoiDung tb_NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MoTaDonHang> tb_MoTaDonHang { get; set; }
    }
}
