//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DanhGiaTraiNghiem
    {
        public int ID { get; set; }
        public Nullable<int> ID_NguoiDung { get; set; }
        public Nullable<int> ID_MatHang { get; set; }
        public string NoiDung { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
    
        public virtual tb_MatHang tb_MatHang { get; set; }
        public virtual tb_NguoiDung tb_NguoiDung { get; set; }
    }
}
