//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web.Mvc;

    public partial class tb_MatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_MatHang()
        {
            this.tb_AnhMatHang = new HashSet<tb_AnhMatHang>();
            this.tb_DanhGiaTraiNghiem = new HashSet<tb_DanhGiaTraiNghiem>();
            this.tb_GioiTinhMatHang = new HashSet<tb_GioiTinhMatHang>();
            this.tb_MauMatHang = new HashSet<tb_MauMatHang>();
            this.tb_MoTaDonHang = new HashSet<tb_MoTaDonHang>();
            this.tb_SanPham = new HashSet<tb_SanPham>();
            this.tb_SizeMatHang = new HashSet<tb_SizeMatHang>();
        }
    
        public int ID { get; set; }
        [DisplayName("ID danh mục")]
        public Nullable<int> ID_DanhMuc { get; set; }

        [DisplayName("Tên mặt hàng")]
        public string TenMatHang { get; set; }

        [DisplayName("Giá")]
        public Nullable<decimal> Gia { get; set; }

        [DisplayName("Số lượng sản phẩm")]
        public Nullable<int> SoLuongSanPham { get; set; }

        [DisplayName("Đã bán")]
        public Nullable<int> DaBan { get; set; }

        [DisplayName("Giảm giá")]
        public Nullable<int> GiamGia { get; set; }

        [DisplayName("Mô tả")]
        [AllowHtml]
        public string MoTa { get; set; }

        [DisplayName("Ảnh mô tả")]
        public string AnhMoTa { get; set; }

        [DisplayName("Đánh giá")]
        public Nullable<double> Rating { get; set; }

        [DisplayName("Ngày thêm")]
        public Nullable<System.DateTime> NgayThem { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AnhMatHang> tb_AnhMatHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DanhGiaTraiNghiem> tb_DanhGiaTraiNghiem { get; set; }
        public virtual tb_DanhMuc tb_DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_GioiTinhMatHang> tb_GioiTinhMatHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MauMatHang> tb_MauMatHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MoTaDonHang> tb_MoTaDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SanPham> tb_SanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SizeMatHang> tb_SizeMatHang { get; set; }
    }
}
