//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_NguoiDung()
        {
            this.tb_DanhGiaTraiNghiem = new HashSet<tb_DanhGiaTraiNghiem>();
            this.tb_DonMuaHang = new HashSet<tb_DonMuaHang>();
        }
    
        public int ID { get; set; }
        [DisplayName("Tên đăng nhập")]
        public string TenDangNhap { get; set; }

        [DisplayName("Mật khẩu")]
        public string MatKhau { get; set; }

        [DisplayName("Tên hiển thị")]
        public string TenHienThi { get; set; }

        [DisplayName("Số điện thoại")]
        public string SDT { get; set; }

        [DisplayName("Email")]
        public string Email { get; set; }

        [DisplayName("Giới tính")]
        public Nullable<int> GioiTinh { get; set; }

        [DisplayName("Ngày sinh")]
        public Nullable<System.DateTime> NgaySinh { get; set; }

        [DisplayName("Địa chỉ")]
        public string DiaChi { get; set; }

        [DisplayName("Ảnh đại diện")]
        public string AnhDaiDien { get; set; }

        [DisplayName("Trạng thái")]
        public Nullable<bool> TrangThai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DanhGiaTraiNghiem> tb_DanhGiaTraiNghiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DonMuaHang> tb_DonMuaHang { get; set; }
    }
}
