//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SizeMatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_SizeMatHang()
        {
            this.tb_SanPham = new HashSet<tb_SanPham>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_MatHang { get; set; }
        public Nullable<int> ID_KichThuoc { get; set; }
    
        public virtual tb_BangKichThuoc tb_BangKichThuoc { get; set; }
        public virtual tb_MatHang tb_MatHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SanPham> tb_SanPham { get; set; }
    }
}
